# YouTube Info Analyzer - Konfiguration
# Ocean Theme Config für persönliches Wissensmanagement

# Secret Service Konfiguration (KeePassXC via D-Bus)
secrets:
  trilium_service: "TrilliumToken"
  trilium_username: "token"
  nextcloud_service: "NextcloudPW"
  nextcloud_username: "steefen"

whisper:
  enabled: true  

# Analyse-Regeln mit Prompt-Dateien
rules:
  fachinhalt:
    file: "prompts/fachinhalt.md"
    weight: 0.35
    enabled: true
    
  qualität:
    file: "prompts/qualität.md" 
    weight: 0.25
    enabled: true
    
  länge_tiefe:
    file: "prompts/länge_tiefe.md"
    weight: 0.20
    enabled: true
    
  relevanz:
    file: "prompts/relevanz.md"
    weight: 0.20
    enabled: true

# Bewertungseinstellungen
scoring:
  threshold: 0.7          # Mindest-Score für Video Download (0.0-1.0)
  min_confidence: 0.6     # Mindest-Konfidenz der KI-Bewertung

# Speicher-Konfiguration
storage:
  nextcloud_path: "/YouTube-Archive"
  trilium_parent_note: "YouTube Knowledge Base"
  sqlite_path: "data/youtube_analyzer.db"
