ollama:
  host: http://localhost:11434
  max_tokens: 4000
  model: gemma3:4b
  temperature: 0.2
  timeout: 300
processing:
  audio_format: mp3
  cleanup_temp_files: true
  max_video_length: 7200
  temp_folder: /tmp/youtube_analyzer
  video_format: mp4
rules:
  fachinhalt:
    enabled: true
    file: prompts/fachinhalt.md
    weight: 0.35
  l채nge_tiefe:
    enabled: true
    file: prompts/l채nge_tiefe.md
    weight: 0.2
  qualit채t:
    enabled: true
    file: prompts/qualit채t.md
    weight: 0.25
  relevanz:
    enabled: true
    file: prompts/relevanz.md
    weight: 0.2
scoring:
  min_confidence: 0.6
  threshold: 0.7
secrets:
  nextcloud_service: NextcloudPW
  nextcloud_username: steefen
  trilium_service: TrilliumToken
  trilium_username: token
storage:
  nextcloud_path: /YouTube-Archive
  sqlite_path: data/youtube_analyzer.db
  trilium_parent_note: YouTube Knowledge Base
whisper:
  compute_type: float16
  device: cuda
  enabled: true
  language: null
  model: large-v3
