llm_processing:
  max_tokens: 4000
  model: gpt-4
  provider: openai
  retry_attempts: 5
  retry_delay: 5
  system_prompt_file: prompts/transcript_processing.md
  temperature: 0.1
  timeout: 300
ollama:
  host: http://localhost:11434
  max_tokens: 4000
  model: gemma2
  temperature: 0.1
  timeout: 300
processing:
  audio_format: mp3
  cleanup_temp_files: true
  max_video_length: 7200
  temp_folder: /tmp/youtube_analyzer
  video_format: mp4
rules:
  fachinhalt:
    enabled: true
    file: prompts/fachinhalt.md
    weight: 0.35
  l채nge_tiefe:
    enabled: true
    file: prompts/l채nge_tiefe.md
    weight: 0.2
  qualit채t:
    enabled: true
    file: prompts/qualit채t.md
    weight: 0.25
  relevanz:
    enabled: true
    file: prompts/relevanz.md
    weight: 0.2
scoring:
  min_confidence: 0.6
  threshold: 0.7
secrets:
  anthropic_service: Anthropic_API_Key
  anthropic_username: api_key
  google_service: Google_API_Key
  google_username: api_key
  nextcloud_service: NextcloudPW
  nextcloud_username: steefen
  openai_service: OpenAI_API_Key
  openai_username: api_key
  trilium_service: TrilliumToken
  trilium_username: token
storage:
  nextcloud_base_url: https://nextcloud.example.com/remote.php/dav/files/username/
  nextcloud_path: /YouTube-Archive
  sqlite_path: data/youtube_analyzer.db
  trilium_parent_note: YouTube Knowledge Base
trilium_upload:
  auto_tags:
  - youtube
  - transcript
  - llm-processed
  base_url: https://trilium.example.com
  enabled: true
  include_metadata: true
  note_template: transcript
  parent_note_id: YouTube Transcripts
  timeout: 60
whisper:
  compute_type: float16
  device: cuda
  enabled: true
  language: null
  model: large-v3
